###
# @name login
curl -X POST http://localhost:3333/api/login -d '{"username": "woizpass", "password": "test"}' -H "Content-Type: application/json"

#### 
# @name logout
@authToken = {{login.response.body.idToken}}
curl -X POST http://localhost:3333/api/logout -d '{}' -H "Authorization: Bearer {{authToken}}" -H "Content-Type: application/json"
